global root "."
global input "$root/01_data/01_input"
global data_scripts "$root/01_data/02_scripts"
global cleaned "$root/01_data/03_cleaned_data"
global analysis_scripts "$root/02_analysis/02_scripts"
global output "$root/02_analysis/03_outputs"
global robust_scripts "$root/03_robustness/02_scripts"
global robust_output "$root/03_robustness/03_outputs"


do "$data_scripts/01_import_households.do"
do "$data_scripts/02_import_transactions_2023.do"
do "$data_scripts/03_import_transactions_2024.do"
do "$data_scripts/04_append_transactions.do"
do "$data_scripts/05_prepare_products.do"
do "$data_scripts/06_prepare_demographics.do"
do "$data_scripts/07_prepare_policy_flags.do"
do "$data_scripts/08_merge_households_transactions.do"
do "$data_scripts/09_merge_products.do"
do "$data_scripts/10_merge_demographics.do"
do "$data_scripts/11_merge_policy_flags.do"
do "$data_scripts/12_enrich_region.do"
